// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh_u3yzuKpY3qAC5FmV0ORXt3z32U6H_U',
    appId: '1:345587559400:web:f75687b7b0c48d307ed25d',
    messagingSenderId: '345587559400',
    projectId: 'flutterfire-ui-codelab-5cf42',
    authDomain: 'flutterfire-ui-codelab-5cf42.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-5cf42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOpCD76IvzrSB7NTu0EfUrJRstdwH9P9U',
    appId: '1:345587559400:android:4e0de4a686218c467ed25d',
    messagingSenderId: '345587559400',
    projectId: 'flutterfire-ui-codelab-5cf42',
    storageBucket: 'flutterfire-ui-codelab-5cf42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeL5hBzI6IOZgz4H9QIILTZxqjVF_9J94',
    appId: '1:345587559400:ios:722bb67f44bad37e7ed25d',
    messagingSenderId: '345587559400',
    projectId: 'flutterfire-ui-codelab-5cf42',
    storageBucket: 'flutterfire-ui-codelab-5cf42.appspot.com',
    iosClientId: '345587559400-2oen3dfhu89i4a4c4qbtdb0ncog4l633.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeL5hBzI6IOZgz4H9QIILTZxqjVF_9J94',
    appId: '1:345587559400:ios:51e5f64ef2cd793d7ed25d',
    messagingSenderId: '345587559400',
    projectId: 'flutterfire-ui-codelab-5cf42',
    storageBucket: 'flutterfire-ui-codelab-5cf42.appspot.com',
    iosClientId: '345587559400-1n33rgs5h2351rh0i5ctatmmlvbioa7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
